"""add_en_ps_content_fields

Revision ID: 524c1de71453
Revises: b7c8d9e0f1a2
Create Date: 2026-09-02 22:07:28.822444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '524c1de71453'
down_revision: Union[str, None] = 'b7c8d9e0f1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('title_en', sa.String(length=160), nullable=True))
    op.add_column('articles', sa.Column('title_ps', sa.String(length=160), nullable=True))
    op.add_column('articles', sa.Column('excerpt_en', sa.String(length=300), nullable=True))
    op.add_column('articles', sa.Column('excerpt_ps', sa.String(length=300), nullable=True))
    op.add_column('articles', sa.Column('body_en', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('body_ps', sa.Text(), nullable=True))
    op.add_column('branches', sa.Column('name_en', sa.String(length=120), nullable=True))
    op.add_column('branches', sa.Column('name_ps', sa.String(length=120), nullable=True))
    op.add_column('branches', sa.Column('city_en', sa.String(length=80), nullable=True))
    op.add_column('branches', sa.Column('city_ps', sa.String(length=80), nullable=True))
    op.add_column('branches', sa.Column('country_en', sa.String(length=80), nullable=True))
    op.add_column('branches', sa.Column('country_ps', sa.String(length=80), nullable=True))
    op.add_column('branches', sa.Column('address_en', sa.Text(), nullable=True))
    op.add_column('branches', sa.Column('address_ps', sa.Text(), nullable=True))
    op.add_column('currencies', sa.Column('name_en', sa.String(length=80), nullable=True))
    op.add_column('currencies', sa.Column('name_ps', sa.String(length=80), nullable=True))
    op.drop_index('uq_currencies_rate_source_code', table_name='currencies')
    op.create_index(op.f('ix_currencies_rate_source'), 'currencies', ['rate_source'], unique=False)
    op.add_column('faqs', sa.Column('question_en', sa.String(length=200), nullable=True))
    op.add_column('faqs', sa.Column('question_ps', sa.String(length=200), nullable=True))
    op.add_column('faqs', sa.Column('answer_en', sa.Text(), nullable=True))
    op.add_column('faqs', sa.Column('answer_ps', sa.Text(), nullable=True))
    op.add_column('services', sa.Column('title_en', sa.String(length=120), nullable=True))
    op.add_column('services', sa.Column('title_ps', sa.String(length=120), nullable=True))
    op.add_column('services', sa.Column('summary_en', sa.Text(), nullable=True))
    op.add_column('services', sa.Column('summary_ps', sa.Text(), nullable=True))
    op.add_column('site_settings', sa.Column('value_en', sa.Text(), nullable=True))
    op.add_column('site_settings', sa.Column('value_ps', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'value_ps')
    op.drop_column('site_settings', 'value_en')
    op.drop_column('services', 'summary_ps')
    op.drop_column('services', 'summary_en')
    op.drop_column('services', 'title_ps')
    op.drop_column('services', 'title_en')
    op.drop_column('faqs', 'answer_ps')
    op.drop_column('faqs', 'answer_en')
    op.drop_column('faqs', 'question_ps')
    op.drop_column('faqs', 'question_en')
    op.drop_index(op.f('ix_currencies_rate_source'), table_name='currencies')
    op.create_index('uq_currencies_rate_source_code', 'currencies', ['rate_source', 'code'], unique=False)
    op.drop_column('currencies', 'name_ps')
    op.drop_column('currencies', 'name_en')
    op.drop_column('branches', 'address_ps')
    op.drop_column('branches', 'address_en')
    op.drop_column('branches', 'country_ps')
    op.drop_column('branches', 'country_en')
    op.drop_column('branches', 'city_ps')
    op.drop_column('branches', 'city_en')
    op.drop_column('branches', 'name_ps')
    op.drop_column('branches', 'name_en')
    op.drop_column('articles', 'body_ps')
    op.drop_column('articles', 'body_en')
    op.drop_column('articles', 'excerpt_ps')
    op.drop_column('articles', 'excerpt_en')
    op.drop_column('articles', 'title_ps')
    op.drop_column('articles', 'title_en')
    # ### end Alembic commands ###
