"""add_comment_parent_id

Revision ID: 88236b3a72b1
Revises: 6b160bcb73da
Create Date: 2026-08-13 22:22:21.258701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '88236b3a72b1'
down_revision: Union[str, None] = '6b160bcb73da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('parent_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_comments_parent_id'), 'comments', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'comments', 'comments', ['parent_id'], ['id'], ondelete='CASCADE')
    op.execute("UPDATE comments SET is_approved = true WHERE is_approved = false")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_index(op.f('ix_comments_parent_id'), table_name='comments')
    op.drop_column('comments', 'parent_id')
    # ### end Alembic commands ###
