/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as RatesRouteImport } from './routes/rates'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as AuthenticatedDashboardRouteRouteImport } from './routes/_authenticated/dashboard/route'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as ManageSplatRouteImport } from './routes/manage.$'
import { Route as UploadsSplatRouteImport } from './routes/uploads/$'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardBlogRouteImport } from './routes/_authenticated/dashboard/blog'
import { Route as AuthenticatedDashboardBranchesRouteImport } from './routes/_authenticated/dashboard/branches'
import { Route as AuthenticatedDashboardCommentsRouteImport } from './routes/_authenticated/dashboard/comments'
import { Route as AuthenticatedDashboardFaqsRouteImport } from './routes/_authenticated/dashboard/faqs'
import { Route as AuthenticatedDashboardFeedbackRouteImport } from './routes/_authenticated/dashboard/feedback'
import { Route as AuthenticatedDashboardPagesRouteImport } from './routes/_authenticated/dashboard/pages'
import { Route as AuthenticatedDashboardRatesRouteImport } from './routes/_authenticated/dashboard/rates'
import { Route as AuthenticatedDashboardServicesRouteImport } from './routes/_authenticated/dashboard/services'
import { Route as AuthenticatedDashboardTransfersRouteImport } from './routes/_authenticated/dashboard/transfers'
import { Route as AuthenticatedDashboardUsersRouteImport } from './routes/_authenticated/dashboard/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const RatesRoute = RatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageSplatRoute = ManageSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ManageRoute,
} as any)
const UploadsSplatRoute = UploadsSplatRouteImport.update({
  id: '/uploads/$',
  path: '/uploads/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardBlogRoute =
  AuthenticatedDashboardBlogRouteImport.update({
    id: '/blog',
    path: '/blog',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardBranchesRoute =
  AuthenticatedDashboardBranchesRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardCommentsRoute =
  AuthenticatedDashboardCommentsRouteImport.update({
    id: '/comments',
    path: '/comments',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardFaqsRoute =
  AuthenticatedDashboardFaqsRouteImport.update({
    id: '/faqs',
    path: '/faqs',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardFeedbackRoute =
  AuthenticatedDashboardFeedbackRouteImport.update({
    id: '/feedback',
    path: '/feedback',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardPagesRoute =
  AuthenticatedDashboardPagesRouteImport.update({
    id: '/pages',
    path: '/pages',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardRatesRoute =
  AuthenticatedDashboardRatesRouteImport.update({
    id: '/rates',
    path: '/rates',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardServicesRoute =
  AuthenticatedDashboardServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardTransfersRoute =
  AuthenticatedDashboardTransfersRouteImport.update({
    id: '/transfers',
    path: '/transfers',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardUsersRoute =
  AuthenticatedDashboardUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/branches': typeof BranchesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/feedback': typeof FeedbackRoute
  '/manage': typeof ManageRouteWithChildren
  '/rates': typeof RatesRoute
  '/services': typeof ServicesRoute
  '/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/manage/$': typeof ManageSplatRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/articles/': typeof ArticlesIndexRoute
  '/dashboard/blog': typeof AuthenticatedDashboardBlogRoute
  '/dashboard/branches': typeof AuthenticatedDashboardBranchesRoute
  '/dashboard/comments': typeof AuthenticatedDashboardCommentsRoute
  '/dashboard/faqs': typeof AuthenticatedDashboardFaqsRoute
  '/dashboard/feedback': typeof AuthenticatedDashboardFeedbackRoute
  '/dashboard/pages': typeof AuthenticatedDashboardPagesRoute
  '/dashboard/rates': typeof AuthenticatedDashboardRatesRoute
  '/dashboard/services': typeof AuthenticatedDashboardServicesRoute
  '/dashboard/transfers': typeof AuthenticatedDashboardTransfersRoute
  '/dashboard/users': typeof AuthenticatedDashboardUsersRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/branches': typeof BranchesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/feedback': typeof FeedbackRoute
  '/manage': typeof ManageRouteWithChildren
  '/rates': typeof RatesRoute
  '/services': typeof ServicesRoute
  '/api/$': typeof ApiSplatRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/manage/$': typeof ManageSplatRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/articles': typeof ArticlesIndexRoute
  '/dashboard/blog': typeof AuthenticatedDashboardBlogRoute
  '/dashboard/branches': typeof AuthenticatedDashboardBranchesRoute
  '/dashboard/comments': typeof AuthenticatedDashboardCommentsRoute
  '/dashboard/faqs': typeof AuthenticatedDashboardFaqsRoute
  '/dashboard/feedback': typeof AuthenticatedDashboardFeedbackRoute
  '/dashboard/pages': typeof AuthenticatedDashboardPagesRoute
  '/dashboard/rates': typeof AuthenticatedDashboardRatesRoute
  '/dashboard/services': typeof AuthenticatedDashboardServicesRoute
  '/dashboard/transfers': typeof AuthenticatedDashboardTransfersRoute
  '/dashboard/users': typeof AuthenticatedDashboardUsersRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/branches': typeof BranchesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/feedback': typeof FeedbackRoute
  '/manage': typeof ManageRouteWithChildren
  '/rates': typeof RatesRoute
  '/services': typeof ServicesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/manage/$': typeof ManageSplatRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/articles/': typeof ArticlesIndexRoute
  '/_authenticated/dashboard/blog': typeof AuthenticatedDashboardBlogRoute
  '/_authenticated/dashboard/branches': typeof AuthenticatedDashboardBranchesRoute
  '/_authenticated/dashboard/comments': typeof AuthenticatedDashboardCommentsRoute
  '/_authenticated/dashboard/faqs': typeof AuthenticatedDashboardFaqsRoute
  '/_authenticated/dashboard/feedback': typeof AuthenticatedDashboardFeedbackRoute
  '/_authenticated/dashboard/pages': typeof AuthenticatedDashboardPagesRoute
  '/_authenticated/dashboard/rates': typeof AuthenticatedDashboardRatesRoute
  '/_authenticated/dashboard/services': typeof AuthenticatedDashboardServicesRoute
  '/_authenticated/dashboard/transfers': typeof AuthenticatedDashboardTransfersRoute
  '/_authenticated/dashboard/users': typeof AuthenticatedDashboardUsersRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/branches'
    | '/contact'
    | '/faq'
    | '/feedback'
    | '/manage'
    | '/rates'
    | '/services'
    | '/dashboard'
    | '/api/$'
    | '/articles/$slug'
    | '/manage/$'
    | '/uploads/$'
    | '/articles/'
    | '/dashboard/blog'
    | '/dashboard/branches'
    | '/dashboard/comments'
    | '/dashboard/faqs'
    | '/dashboard/feedback'
    | '/dashboard/pages'
    | '/dashboard/rates'
    | '/dashboard/services'
    | '/dashboard/transfers'
    | '/dashboard/users'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/branches'
    | '/contact'
    | '/faq'
    | '/feedback'
    | '/manage'
    | '/rates'
    | '/services'
    | '/api/$'
    | '/articles/$slug'
    | '/manage/$'
    | '/uploads/$'
    | '/articles'
    | '/dashboard/blog'
    | '/dashboard/branches'
    | '/dashboard/comments'
    | '/dashboard/faqs'
    | '/dashboard/feedback'
    | '/dashboard/pages'
    | '/dashboard/rates'
    | '/dashboard/services'
    | '/dashboard/transfers'
    | '/dashboard/users'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/branches'
    | '/contact'
    | '/faq'
    | '/feedback'
    | '/manage'
    | '/rates'
    | '/services'
    | '/_authenticated/dashboard'
    | '/api/$'
    | '/articles/$slug'
    | '/manage/$'
    | '/uploads/$'
    | '/articles/'
    | '/_authenticated/dashboard/blog'
    | '/_authenticated/dashboard/branches'
    | '/_authenticated/dashboard/comments'
    | '/_authenticated/dashboard/faqs'
    | '/_authenticated/dashboard/feedback'
    | '/_authenticated/dashboard/pages'
    | '/_authenticated/dashboard/rates'
    | '/_authenticated/dashboard/services'
    | '/_authenticated/dashboard/transfers'
    | '/_authenticated/dashboard/users'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BranchesRoute: typeof BranchesRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  FeedbackRoute: typeof FeedbackRoute
  ManageRoute: typeof ManageRouteWithChildren
  RatesRoute: typeof RatesRoute
  ServicesRoute: typeof ServicesRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  UploadsSplatRoute: typeof UploadsSplatRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rates': {
      id: '/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof RatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/$': {
      id: '/manage/$'
      path: '/$'
      fullPath: '/manage/$'
      preLoaderRoute: typeof ManageSplatRouteImport
      parentRoute: typeof ManageRoute
    }
    '/uploads/$': {
      id: '/uploads/$'
      path: '/uploads/$'
      fullPath: '/uploads/$'
      preLoaderRoute: typeof UploadsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/blog': {
      id: '/_authenticated/dashboard/blog'
      path: '/blog'
      fullPath: '/dashboard/blog'
      preLoaderRoute: typeof AuthenticatedDashboardBlogRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/branches': {
      id: '/_authenticated/dashboard/branches'
      path: '/branches'
      fullPath: '/dashboard/branches'
      preLoaderRoute: typeof AuthenticatedDashboardBranchesRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/comments': {
      id: '/_authenticated/dashboard/comments'
      path: '/comments'
      fullPath: '/dashboard/comments'
      preLoaderRoute: typeof AuthenticatedDashboardCommentsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/faqs': {
      id: '/_authenticated/dashboard/faqs'
      path: '/faqs'
      fullPath: '/dashboard/faqs'
      preLoaderRoute: typeof AuthenticatedDashboardFaqsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/feedback': {
      id: '/_authenticated/dashboard/feedback'
      path: '/feedback'
      fullPath: '/dashboard/feedback'
      preLoaderRoute: typeof AuthenticatedDashboardFeedbackRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/pages': {
      id: '/_authenticated/dashboard/pages'
      path: '/pages'
      fullPath: '/dashboard/pages'
      preLoaderRoute: typeof AuthenticatedDashboardPagesRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/rates': {
      id: '/_authenticated/dashboard/rates'
      path: '/rates'
      fullPath: '/dashboard/rates'
      preLoaderRoute: typeof AuthenticatedDashboardRatesRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/services': {
      id: '/_authenticated/dashboard/services'
      path: '/services'
      fullPath: '/dashboard/services'
      preLoaderRoute: typeof AuthenticatedDashboardServicesRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/transfers': {
      id: '/_authenticated/dashboard/transfers'
      path: '/transfers'
      fullPath: '/dashboard/transfers'
      preLoaderRoute: typeof AuthenticatedDashboardTransfersRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/users': {
      id: '/_authenticated/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof AuthenticatedDashboardUsersRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
  }
}

interface AuthenticatedDashboardRouteRouteChildren {
  AuthenticatedDashboardBlogRoute: typeof AuthenticatedDashboardBlogRoute
  AuthenticatedDashboardBranchesRoute: typeof AuthenticatedDashboardBranchesRoute
  AuthenticatedDashboardCommentsRoute: typeof AuthenticatedDashboardCommentsRoute
  AuthenticatedDashboardFaqsRoute: typeof AuthenticatedDashboardFaqsRoute
  AuthenticatedDashboardFeedbackRoute: typeof AuthenticatedDashboardFeedbackRoute
  AuthenticatedDashboardPagesRoute: typeof AuthenticatedDashboardPagesRoute
  AuthenticatedDashboardRatesRoute: typeof AuthenticatedDashboardRatesRoute
  AuthenticatedDashboardServicesRoute: typeof AuthenticatedDashboardServicesRoute
  AuthenticatedDashboardTransfersRoute: typeof AuthenticatedDashboardTransfersRoute
  AuthenticatedDashboardUsersRoute: typeof AuthenticatedDashboardUsersRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteRouteChildren: AuthenticatedDashboardRouteRouteChildren =
  {
    AuthenticatedDashboardBlogRoute: AuthenticatedDashboardBlogRoute,
    AuthenticatedDashboardBranchesRoute: AuthenticatedDashboardBranchesRoute,
    AuthenticatedDashboardCommentsRoute: AuthenticatedDashboardCommentsRoute,
    AuthenticatedDashboardFaqsRoute: AuthenticatedDashboardFaqsRoute,
    AuthenticatedDashboardFeedbackRoute: AuthenticatedDashboardFeedbackRoute,
    AuthenticatedDashboardPagesRoute: AuthenticatedDashboardPagesRoute,
    AuthenticatedDashboardRatesRoute: AuthenticatedDashboardRatesRoute,
    AuthenticatedDashboardServicesRoute: AuthenticatedDashboardServicesRoute,
    AuthenticatedDashboardTransfersRoute: AuthenticatedDashboardTransfersRoute,
    AuthenticatedDashboardUsersRoute: AuthenticatedDashboardUsersRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteRouteWithChildren =
  AuthenticatedDashboardRouteRoute._addFileChildren(
    AuthenticatedDashboardRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRouteRoute:
    AuthenticatedDashboardRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ManageRouteChildren {
  ManageSplatRoute: typeof ManageSplatRoute
}

const ManageRouteChildren: ManageRouteChildren = {
  ManageSplatRoute: ManageSplatRoute,
}

const ManageRouteWithChildren =
  ManageRoute._addFileChildren(ManageRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BranchesRoute: BranchesRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  FeedbackRoute: FeedbackRoute,
  ManageRoute: ManageRouteWithChildren,
  RatesRoute: RatesRoute,
  ServicesRoute: ServicesRoute,
  ApiSplatRoute: ApiSplatRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  UploadsSplatRoute: UploadsSplatRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
